version: '2'
services:
    gefond-app:
        image: gefond
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gefond-postgresql:5432/GeFond
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gefond-postgresql:
        extends:
            file: postgresql.yml
            service: gefond-postgresql
